name: Pre-Commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  preCommit:
    name: Pre-Commit
    runs-on: eks
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute pre-commit
        # Run all pre-commit checks on max version supported